version: 2.1
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn

      - run:
          name: Run Test cases
          command: yarn test

